### ISSUE TITLE
Let's not automatically remember user and password?

### ISSUE THREAD

**Issue by mjhowell** [enaess/network-manager-sstp#12]
The VPN tab of the connection editor takes username and password. If I leave blank, it requests user name and password when I try to connect. Once I have supplied the user name and password, it seems to remember it (doesn't ask again when I reconnect later).

I'd prefer that this behaved like the PPTP VPN connection editor, which has a Saved / Always Ask / Required selection in the UI, so I have the option to always manually enter the password when connecting. Screenshots attached for comparison.

I'm using the 0.9.8.8 release debs for ubuntu on Trusty.

I'm happy to work on this, with some guidance... there is code at sourceforge and at github, and it's not clear what commit was used for building for Trusty, before conversion to newer Network Manager. Ideally I'd like to have something that works for Trusty while also getting the task done for newer releases (Xenial is imminent) and other releases and distros using Network Manager.

![create-pptp-sstp](https://cloud.githubusercontent.com/assets/2798606/14645360/38ed8d04-060a-11e6-8fad-8398006e40c5.png)

![create-pptp-vpn](https://cloud.githubusercontent.com/assets/2798606/14645359/38ecd81e-060a-11e6-9f79-8939ed6e0dbb.png)

**Comment by enaess** [comment]
Hi, 
The current source repository already have this feature of asking users for their password, and also storing it. I realize that this is likely for newer distributions as I am successfully running that configuration on Ubuntu 15.10. Latest update pending release to support upgraded version of NetworkManager and their libraries to 16.04 and that is all in source code repository.

Regards,
- Eivind

**Comment by mjhowell** [comment]
Thanks Eivind. 

Is this github repo your current official source? (i.e. not something at sourceforge?)

Also your current official source for sstp-client, is that the SVN at sourceforge? I see a repo here on github but it has not been touched in a while...

**Comment by enaess** [comment]
That is correct, I somehow ended up with a git repository on github and a subversion repository on sourceforge. They are both up to date with the latest code, notably the one for network-manager have been updated with the latest patches for the upcoming release of Ubuntu 16.04 w/required NetworkManager changes. These might not compile on your 14.04 distribution however, but they do have the password credential changes you requested.

I may update sstp-client with some additional patches to setting the ppp version for Ubuntu.

Regards
