### ISSUE TITLE
PPA for Ubuntu 17.04

### ISSUE THREAD

**Issue by pixelipo** [enaess/network-manager-sstp#20]
Any chance to get the [PPA](https://launchpad.net/%7Eeivnaes/+archive/ubuntu/network-manager-sstp) updated to support Ubuntu 17.04?

Thanks

**Comment by brianfreytag** [comment]
[+1] Also would like to see 17.10

**Comment by enaess** [comment]
Just had the sstp-client re-built for the network-manager-sstp PPA off launchpad yesterday. The network-manager-sstp takes a bit longer because there are changes I had to port from the pptp package. I'll need your help in QA this though.

**Comment by Russell-Jones-OxPhys** [comment]
Thanks for sorting this :) It works nicely for me on Ubuntu Artful thus far. One minor snag: the network-manager-sstp package doesn't seem to depend on sstp-client, but won't work without it.

**Comment by enaess** [comment]
Thanks for giving this package a spin. I'll look into the package dependencies (thanks for reporting that). QA general functionality and if all the bells and whistles works in your environment, thumbs up. Others will have to report how it doesn't or does work in their environment. Kind of the nature of open source development.
