### ISSUE TITLE
Errors when attempting to build from source

### ISSUE THREAD

**Issue by terikin** [enaess/network-manager-sstp#23]
I'm running Ubuntu 17.10.
It looks like the PPA is only for earlier versions, so I tried building from source.
My problems may well just arise out of ignorance, but I cloned the git repo and then ran autogen.sh, but it gave the following error:
configure.ac:68: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
I'm guessing I'm just missing a dependency; I looked in the README (as well as several other files), but I haven't found a list of dependencies.  Is there a list somewhere that I'm missing?
Thanks!

**Comment by terikin** [comment]
Well, I got it building at least (still troubleshooting actually connecting to my VPN, but that's another story).
Here's what I installed as dependencies; I didn't try to check whether I had anything else installed, and these may well be listed with Network Manager, just not with the sstp client:
libglib2.0-dev libgtk-3-dev libnma-dev libsecret-1-dev libnm-gtk-dev libnm-glib-vpn-dev

**Comment by enaess** [comment]
I've ported the latest changes to network-manager-sstp from the corresponding pptp package. I expect a release is imminent soon. I'd need your help to QA this though.

**Comment by terikin** [comment]
Sorry for the delay - I've been swamped for the last couple weeks.  I've
been using your sstp-client release for Ubuntu artful for the past day
or so, and it's been working reliably.

It seems a good bit slower than I'd expect when checking out a
subversion repository over the VPN.  I don't know all the ramifications,
but this specific repo is using svn over ssh, and it has lots of small
files.  I can use RDP fairly well, although it definitely lags more than
if I use the Windows RDP client connected using the Windows VPN client. 
Dunno how much of that is the RDP client versus the VPN though.
