### ISSUE TITLE
make Ubuntu package for network-manager-sstp depend on sstp-client

### ISSUE THREAD

**Issue by tpapp** [enaess/network-manager-sstp#24]
This affects the recent builds, eg `1.2.4-0ubuntu3`. When `sstp-client` is not available, the VPN connection fails with
```
VPN connection: failed to connect: 'Could not find sstp client binary.'
```
in `syslog`.

Installing `sstp-client` manually of course solves this.

**Comment by enaess** [comment]
That's a good idea. The current package specification per launchpad does include sstp-client as a part of the dependency list. I did try apt-get install network-manager-sstp and this is what I got (19.04). 

udo apt-get install network-manager-sstp
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libsstp-api-0 network-manager-sstp-gnome sstp-client
The following NEW packages will be installed:
  libsstp-api-0 network-manager-sstp network-manager-sstp-gnome sstp-client
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 139 kB/183 kB of archives.
After this operation, 1,120 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu disco/main amd64 network-manager-sstp amd64 1.2.6-0ubuntu2 [111 kB]
Get:2 http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu disco/main amd64 network-manager-sstp-gnome amd64 1.2.6-0ubuntu2 [27.9 kB]
Fetched 139 kB in 1s (103 kB/s)                  
Selecting previously unselected package libsstp-api-0.
(Reading database ... 187422 files and directories currently installed.)
Preparing to unpack .../libsstp-api-0_1.0.12-0ubuntu3_amd64.deb ...
Unpacking libsstp-api-0 (1.0.12-0ubuntu3) ...
Selecting previously unselected package sstp-client.
Preparing to unpack .../sstp-client_1.0.12-0ubuntu3_amd64.deb ...
Unpacking sstp-client (1.0.12-0ubuntu3) ...
Selecting previously unselected package network-manager-sstp.
Preparing to unpack .../network-manager-sstp_1.2.6-0ubuntu2_amd64.deb ...
Unpacking network-manager-sstp (1.2.6-0ubuntu2) ...
Selecting previously unselected package network-manager-sstp-gnome.
Preparing to unpack .../network-manager-sstp-gnome_1.2.6-0ubuntu2_amd64.deb ...
Unpacking network-manager-sstp-gnome (1.2.6-0ubuntu2) ...
Setting up libsstp-api-0 (1.0.12-0ubuntu3) ...
Setting up sstp-client (1.0.12-0ubuntu3) ...
Setting up network-manager-sstp (1.2.6-0ubuntu2) ...
Setting up network-manager-sstp-gnome (1.2.6-0ubuntu2) ...
Processing triggers for man-db (2.8.5-2) ...
Processing triggers for dbus (1.12.12-1ubuntu1) ...
Processing triggers for libc-bin (2.29-0ubuntu2) ...
