### ISSUE TITLE
GUI Gnome not opening 

### ISSUE THREAD

**Issue by rmrten** [enaess/network-manager-sstp#26]
Hey,

when i want to configure VPN and choose in drop down menu of GUI SSTP and hit create i get this error:

Could not load editor VPN plugin for org.freedesktop.NetworkManager.sstp ( The resource at /org/freedesktop/network-manager-ppt/nm-sstp-dialog.ui does not exist.

Understand that GNOME Gui tool is not loading right file but unsure how to reinstall/fix it? 

Installed on Solus OS following this: 

https://solus-project.com/forums/viewtopic.php?f=9&t=9790

Thank you.

**Comment by enaess** [comment]
I just committed a fix to the master branch to fix this. Will need to retest and roll another set of packages. Thanks for reporting this.

**Comment by enaess** [comment]
Let me know if the latest fixes won't do it for you, and then re-open the issue again. Email me directly at eivnaes [at] yahoo [dot] com, to bring it to my attention.
