### ISSUE TITLE
Enable simulaneous Internet connection

### ISSUE THREAD

**Issue by croraf** [enaess/network-manager-sstp#29]
How to enable simultaneous Internet connection when on VPN? I'm on Ubuntu 18.04.

![image](https://user-images.githubusercontent.com/19698636/53798231-1d12ca80-3f38-11e9-990c-7ed5430a4e66.png)

I tried checking "Use this connection only for its resources", and nothing changed.
Then I tried checking and disabling Routes Automatic, but then VPN does not work, just Internet.

**Comment by enaess** [comment]
There are a few different problems here.

I've committed changes in the main branch to handle configuration on the page referenced above. That should work, and routes specified here are added by network manager. 

One corner case is if your DNS pushed by the server doesn't have a route (I'll likely fix that soon), typically a Microsoft Azure problem where you add a route for your VNET, but then misses out a host route to the default DNS server pushed down). The checkbox for "use connection only fore resources on it's network" will manage the default route for you.

The other is a bug on Ubuntu 18.04 and up to current, the ip-up.d/0000usepeerdns script will check if ipparam parameter is any of the nm-l2tp-service-* or nm-pptp-service-*, but misses out on nm-sstp-service-*. I've changed the master branch to use the "pptp" string to bypass this. That's a bug on launchpad https://bugs.launchpad.net/ubuntu/+source/ppp/+bug/1778946

You could try to compile master branch or wait for the new release that support EAP-TLS!
