### ISSUE TITLE
Version constraint on ppp

### ISSUE THREAD

**Issue by Chris00** [enaess/network-manager-sstp#3]
Could you explain the reason of the version constraint on `ppp`, namely `ppp (<< 2.4.6)`?  It compiles fine (and seems to run fine) without it.

**Comment by Cyber1000** [comment]
I'm also interested on this issue. Fedora 21/22 have newer Version of ppp, so NetworkManager-sstp can only be installed with a "nodependency" Flag.

**Comment by enaess** [comment]
I doubt there is any real version constraint on 2.4.5, but it's not yet been fully tested with 2.4.6. I've been working on an update to the project as of lately to bring it up to date with the current network-manager-pptp project.

**Comment by enaess** [comment]
Updated the rpm .spec file to use the version installed of PPP on FC 21/22.

**Comment by sakal** [comment]
Today current available ppp version in debian is 2.4.7-1+2 . May be time to bump requirements?

**Comment by enaess** [comment]
Or remove the upper bound of the requirements. I'll see if I can shoehorn this into my weekend. Thanks for reporting this issue.
