### ISSUE TITLE
Ubuntu 19.10 support

### ISSUE THREAD

**Issue by jpastoor** [enaess/network-manager-sstp#31]
Hello @enaess,

Could you make update the PPA for 19.10 (eoan)?

or maybe lend some insight in how I can get it working with the disco release.
I'm kind of new to this linux package thing, I tried adding the PPA from disco instead 
`deb http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu disco main`

```
The following packages have unmet dependencies:
 network-manager-sstp : Depends: libnm-glib-vpn1 (>= 0.7.999) but it is not installable
                        Depends: libnm-util2 (>= 0.8.998) but it is not installable
                        Depends: ppp (< 2.4.6) but 2.4.7-2+4.1ubuntu4 is to be installed
```

Thanks in advance!

**Comment by enaess** [comment]
Packages being updated and put up on the PPA now. You should be able to use the ppa: http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu eoan main

**Comment by jpastoor** [comment]
Thanks!
