### ISSUE TITLE
install in centos7?

### ISSUE THREAD

**Issue by hffei** [enaess/network-manager-sstp#35]
Please help me to  install network manage SSTP on centos7

**Comment by szpak** [comment]
network-manager-sstp officially is currently packaged [only](https://apps.fedoraproject.org/packages/NetworkManager-sstp) for Fedora. As I don't use CentOS with nm-sstp it would be not feasible for me to maintain a variant for CentOS which I couldn't easily test or debug.
However, as I see [nm-pptp](https://src.fedoraproject.org/rpms/NetworkManager-pptp) is already available in CentOS 7, maybe @lkundrak (which is also heavily involved in nm-sstp in Fedora) would like to keep an eye also on the CentOS 7 version of nm-sstp? :-).

**Comment by enaess** [comment]
@hffei Could you file a request with the CentOS distribution?
