### ISSUE TITLE
Missing package for Ubuntu Focal Fossa (20.04 LTS)

### ISSUE THREAD

**Issue by felipeaf** [enaess/network-manager-sstp#38]
Hi, thank you for your work in this project.
The last Ubuntu LTS, 20.04, was just released (April 23, 2020). The ppa has only packages for eoan (19.10) and older, and that packages has broken dependencies in new 20.04 LTS. 
*I already was able to install by generating new deb files from sstp-client source.

The community would be very greateful if you could make packages available for Ubuntu 20.04.

**Comment by enaess** [comment]
Rebuild is in progress, let me know in an hour or so if this isn't working for you.
