### ISSUE TITLE
Deprication of GnomeKeyring

### ISSUE THREAD

**Issue by alex-eri** [enaess/network-manager-sstp#4]
It does not builds on Arch because of deprication of gnome_keyring_memory_strdup, gnome_keyring_memory_free. If i force build it not start connection:
Dec 29 19:55:39 mini gnome-session[411]: Gjs-Message: JS LOG: Invalid VPN service type (cannot find authentication binary)
Dec 29 19:55:39 mini NetworkManager[15688]: <error> [1419872139.919863] [vpn-manager/nm-vpn-connection.c:1778] get_secrets_cb(): Failed to request VPN secrets #2: (6) N

**Comment by enaess** [comment]
Should be fixed in the latest version.
