### ISSUE TITLE
Support for Ubuntu 21.10

### ISSUE THREAD

**Issue by userneeds-ahe** [enaess/network-manager-sstp#42]
Hi,

I'm having issues installing sstp-client, network-manager-sstp and network-manager-sstp-gnome and its deps on Ubuntu 21.10 (Pop!Os): Among other things, it returns

> The following packages have unmet dependencies:
 sstp-client : Depends: ppp (< 2.4.7-3~) but 2.4.9-1+1ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by enaess** [comment]
Thank you for reporting this. Let me update the build for 21.10 in the next couple of days. By the way, the project URL has moved to https://gitlab.gnome.org/GNOME/network-manager-sstp

**Comment by userneeds-ahe** [comment]
Hi Eivind,
When do you think you have an update on this issue? Perhaps there's a workaround that I'm not aware of. I'm unable to connect to my company VPN because I updated to latest Ubuntu 21.10 and I can't figure out how to get passed the issue with pppd. 
All the best,
Andreas

**Comment by enaess** [comment]
Could you give it a spin?

**Comment by userneeds-ahe** [comment]
Absolutely. I'm on an Ubuntu "impish" and attempting to install network-manager-sstp gives the following error:

> The following packages have unmet dependencies:
 sstp-client : Depends: ppp (< 2.4.7-3~) but 2.4.9-1+1ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.

Seems like i'm missing something...Thanks for your time!

**Comment by userneeds-ahe** [comment]
https://www.reddit.com/r/pop_os/comments/s3qm2t/sstp_fails_install_on_impish_2110/

**Comment by enaess** [comment]
You able to uninstall sstp-client and network-manager? You'd also need to uninstall libsstp-api-0 as well. When I tried last night on a freshly installed ubuntu-desktop 21.10, it made no such complaints. Also, sstp-client doesn't specify a strict dependency on ppp. My last patch to the network-manager-sstp removed it's dependency on the 2.4.7 version of pppd.

sudo apt-get remove sstp-client libsstp-api-0 network-manager-sstp network-manager-sstp-gnome.

I am assuming that you have re-enabled the /etc/apt/sources.list.d/sstp-client.list again after an upgrade, and run apt-get update prior to that.

**Comment by enaess** [comment]
Did that work for you @userneeds-ahe

**Comment by userneeds-ahe** [comment]
Absolutely!

`sudo apt-get remove sstp-client libsstp-api-0 network-manager-sstp network-manager-sstp-gnome.`

Put the following two lines into the following file: /etc/apt/sources.list.d/sstp-client.list 

`deb http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu impish main` 
`deb-src http://ppa.launchpad.net/eivnaes/network-manager-sstp/ubuntu impish main`

and install
`sudo apt-get update
sudo apt install network-manager-sstp sstp-client
`

Thanks Eivind!

**Comment by enaess** [comment]
@userneeds-ahe I just pushed another update. This will allow EAP/MSCHAPV2 authentication.

Do you mind smoke testing it on your setup?

**Comment by enaess** [comment]
Your setup should not be broken, but eap/mschapv2 is still busted in pppd for Ubuntu. Tried to nudge the debian maintainer of the package, and emailed him a patch. Trying to cross list to Ubuntu as well.
