### ISSUE TITLE
network-manager-sstp-gnome compatibility with GTK4

### ISSUE THREAD

**Issue by szpak** [enaess/network-manager-sstp#44]
There is a [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=2064985) of a Fedora user showing that the Gnome configuration dialog doesn't work in with Gnome (42) used in upcoming Fedora 36. I don't have F36 on hand, but it seems to be related to GTK4 also affecting a counterpart for OpenVPN and [linked by](https://bugzilla.redhat.com/show_bug.cgi?id=2057719) the reporter. A related MR in that project: https://gitlab.gnome.org/GNOME/NetworkManager-openvpn/-/merge_requests/41/

I have no experience in making UI for Gnome, but it seems that network-manager-sstp(-gnome) would need to modified to work with Gnome 42.

**Comment by enaess** [comment]
Here is the issue for network-manager-sstp on gitlab.gnome.org
   https://gitlab.gnome.org/GNOME/network-manager-sstp/-/issues/43

I am already working on it.

**Comment by szpak** [comment]
Cool!

In hindsight, I believe, you already told me some time ago about a switch to GitLab :-/.

**Comment by szpak** [comment]
And I see that Tamado also created the linked issue and forgot to mention that in Bugzilla :-).
