### ISSUE TITLE
nm-sstp-service.c:validate_gateway fails when a port is appended to the gateway

### ISSUE THREAD

**Issue by gtjoseph** [enaess/network-manager-sstp#6]
Line 493 should be...

             if (!isalnum (*p) && (*p != '-') && (*p != '.') && (*p != ':'))
instead of

             if (!isalnum (*p) && (*p != '-') && (*p != '.'))

Also the error message at line 535 should show the value instead of the key...

            _("invalid gateway '%s'"),
             value);
instead of 

             _("invalid gateway '%s'"),
             key);

"Invalid gateway 'gateway'" isn't much help. :)

**Comment by enaess** [comment]
Just committed the change to master branch. Thank you for your suggestions.
