### ISSUE TITLE
Configure error.

### ISSUE THREAD

**Issue by bentinata** [enaess/network-manager-sstp#8]
Firstly, got error at configure.ac:

```
configure.ac:62: error: possibly undefined macro: AM_GLIB_GNU_GETTEXT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

Then, got errot at configure:

```
configure: error: cannot find install-sh, install.sh, or shtool in "." "./.." "./../.."
```

Please, update the INSTALLING docs.

**Comment by bentinata** [comment]
Ah, it seems like you write this using Vivid, while my current version is Trusty.

**Comment by enaess** [comment]
The project wasn't updated until Apr 23rd, 2015 to work with the updated Network Manager project. You could sync your git repository to that before April of this year and then compile it for Trusty Thar if you have problems with the more recent changes.
